/**
 * MCP App: inline product grid for buyer-facing shopping tools.
 *
 * A tool that sets `_meta.ui.resourceUri` to {@link SHOPPING_RESULTS_URI} makes a
 * supporting host (Claude Desktop, VS Code, …) render this HTML resource inline
 * in a sandboxed iframe after the call, instead of burying product photos in the
 * collapsed tool-result accordion (which every Claude client does with `image`
 * content blocks). Hosts without MCP Apps support ignore the meta and fall back
 * to the normal text + image-block result, so this is purely additive.
 *
 * The HTML (bundled client + CSS) is generated by scripts/build-shopping-ui.mjs.
 * See ui/shopping-results.client.ts for the view that renders `structuredContent`.
 */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerAppResource, RESOURCE_MIME_TYPE } from "@modelcontextprotocol/ext-apps/server";
import { SHOPPING_RESULTS_HTML } from "./ui/shopping-results.generated.js";

// The URI carries a version segment because at least one host (Claude Desktop)
// caches the resource by URI and never re-reads it after the extension is
// reinstalled — an updated widget silently renders with the OLD html/css until
// the URI changes. Bump the segment whenever the generated HTML changes
// meaningfully; hosts fetch the "new" resource and the stale cache is orphaned.
export const SHOPPING_RESULTS_URI = "ui://firestarter/shopping-results/v3";

// Origins the sandboxed iframe may load product images from. By default an MCP
// App iframe has NO network access; images load only from origins allowlisted
// here (csp.resourceDomains). Seller photos are predominantly Shopify-synced
// (cdn.shopify.com); Firestarter self-hosted blobs live on the API host. A photo
// on any other origin degrades to the "No photo" placeholder rather than a
// broken image — extend this list as new image sources appear in the catalog.
const IMAGE_DOMAINS = [
  "https://cdn.shopify.com",
  "https://api.firestarter.network",
  // Pocodot-pipeline listings (e.g. lst_etSM0EwR) carry photos on this origin
  // today — without it the grid shows "No photo" for every such product. The
  // durable fix is rehost-on-write to /v1/img/<id> (see cli/rehost-listing-images
  // in firestarter-commerce, which already reads a REHOST_HOST_ALLOWLIST env var)
  // so ONE first-party origin covers the whole catalog; keep this list as the
  // stopgap for origins already in the wild.
  "https://cole.pocodot.ai",
];

/**
 * Register the shopping-results UI resource. No-op on server doubles that lack
 * the modern resource API (the unit-test fakes only implement `.tool`), so
 * registering the app can never break the content-only test path.
 */
export function registerShoppingApp(server: McpServer): void {
  if (typeof (server as unknown as { registerResource?: unknown }).registerResource !== "function") return;
  registerAppResource(
    server,
    "Firestarter shopping results",
    SHOPPING_RESULTS_URI,
    { description: "Inline product grid for Firestarter shopping results (photos, price, buyability)." },
    async () => ({
      contents: [{
        uri: SHOPPING_RESULTS_URI,
        mimeType: RESOURCE_MIME_TYPE,
        text: SHOPPING_RESULTS_HTML,
        _meta: {
          ui: {
            csp: { resourceDomains: IMAGE_DOMAINS },
          },
        },
      }],
    }),
  );
}
