/**
 * MCP App: inline product grid for buyer-facing shopping tools.
 *
 * A tool that sets `_meta.ui.resourceUri` to {@link SHOPPING_RESULTS_URI} makes a
 * supporting host (Claude Desktop, VS Code, …) render this HTML resource inline
 * in a sandboxed iframe after the call, instead of burying product photos in the
 * collapsed tool-result accordion (which every Claude client does with `image`
 * content blocks). Hosts without MCP Apps support ignore the meta and fall back
 * to the normal text + image-block result, so this is purely additive.
 *
 * The HTML (bundled client + CSS) is generated by scripts/build-shopping-ui.mjs.
 * See ui/shopping-results.client.ts for the view that renders `structuredContent`.
 */
import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerAppResource, RESOURCE_MIME_TYPE } from "@modelcontextprotocol/ext-apps/server";
import { SHOPPING_RESULTS_HTML } from "./ui/shopping-results.generated.js";

// The URI carries a version segment because at least one host (Claude Desktop)
// caches the resource by URI and never re-reads it after the extension is
// reinstalled — an updated widget silently renders with the OLD html/css until
// the URI changes. Bump the segment whenever the generated HTML changes
// meaningfully; hosts fetch the "new" resource and the stale cache is orphaned.
// v9: seller views — the photo drop zone (upload_request), the listing card
// (listing), and the single-upload confirmation (url). Bytes travel widget →
// host bridge → firestarter_upload_image, never through the model.
// v10: the drop zone gained a COMMUNITY MARKET mode (upload_request.
// market_program_id) — one file, and the hosted URL is handed to
// firestarter_set_market_avatar instead of attached to a listing
// (commerce#1024).
// v11: and a DISPUTE EVIDENCE mode (upload_request.dispute_id) — up to five
// files, each posted to the thread by firestarter_upload_image itself. It does
// not call a dispute tool: those move money, so they are not widgetAccessible
// (commerce#1007).
// v12: and a POSSESSION VERIFICATION mode (upload_request.verify_listing_id) —
// one photo, SUBMITTED for the vision check rather than attached to anything,
// because that shot is evidence, not a product image (commerce#561).
// v13: the uploader honours host-reported safe-area insets. Claude renders MCP
// Apps on mobile in a native WebView and treats anything outside the safe area
// as NOT INTERACTABLE — a drop zone under the chat input is a control the
// seller cannot press, not a cosmetic nit.
// v14: the listing drop zone takes VIDEOS too (MP4/WebM ≤ 25MB, ≤ 3 per
// listing) — clips ride firestarter_upload_video and attach via video_urls;
// activation still keys on a photo. The market, dispute, and verification
// modes stay image-only.
// v15: tier-1 format widening — AVIF photos and QuickTime (.mov) clips join
// the accept lists, matching the API's brand-aware sniffers.
export const SHOPPING_RESULTS_URI = "ui://firestarter/shopping-results/v15";

// The same widget under a URI that NEVER moves, for ChatGPT.
//
// ChatGPT caches the template in its own store keyed by the URI a tool points
// at, and answers "Failed to fetch template" for a URI that store has not
// ingested — so the version bump above, which is the only thing that can ever
// refresh Claude Desktop, is precisely what breaks ChatGPT. Shipping 2.15.0
// moved v5 → v7 and every ChatGPT connector holding v5 stopped rendering.
//
// The two hosts read different keys, so they can be pointed at different URIs:
// `_meta.ui.resourceUri` (the standard, which Claude Desktop reads) keeps the
// version segment, and `_meta["openai/outputTemplate"]` — ChatGPT's own alias,
// attached in tools.ts — carries this one. Both serve identical HTML, and a
// contract test asserts they cannot drift. Do not version this string.
//
// v8: the detail view stays in the chat instead of asking the host for a panel
// or fullscreen, and the hero photo opens at full size in place of the link
// chips.
export const SHOPPING_RESULTS_STABLE_URI = "ui://firestarter/shopping-results";

// Origins the sandboxed iframe may load product images from. By default an MCP
// App iframe has NO network access; images load only from origins allowlisted
// here (csp.resourceDomains). Seller photos are predominantly Shopify-synced
// (cdn.shopify.com); Firestarter self-hosted blobs live on the API host. A photo
// on any other origin degrades to the "No photo" placeholder rather than a
// broken image — extend this list as new image sources appear in the catalog.
const IMAGE_DOMAINS = [
  "https://cdn.shopify.com",
  "https://api.firestarter.network",
  // Pocodot-pipeline listings (e.g. lst_etSM0EwR) carry photos on this origin
  // today — without it the grid shows "No photo" for every such product. The
  // durable fix is rehost-on-write to /v1/img/<id> (see cli/rehost-listing-images
  // in firestarter-commerce, which already reads a REHOST_HOST_ALLOWLIST env var)
  // so ONE first-party origin covers the whole catalog; keep this list as the
  // stopgap for origins already in the wild.
  "https://cole.pocodot.ai",
];

/**
 * Register the shopping-results UI resource. No-op on server doubles that lack
 * the modern resource API (the unit-test fakes only implement `.tool`), so
 * registering the app can never break the content-only test path.
 */
export function registerShoppingApp(server: McpServer): void {
  if (typeof (server as unknown as { registerResource?: unknown }).registerResource !== "function") return;
  // One document, two URIs — see SHOPPING_RESULTS_STABLE_URI for why the hosts
  // are pointed at different ones. Registered from a single body so the HTML,
  // the CSP allowlist and the widget description cannot drift between them.
  const serve = (uri: string) => async () => ({
    contents: [{
      uri,
      mimeType: RESOURCE_MIME_TYPE,
      text: SHOPPING_RESULTS_HTML,
      _meta: {
        ui: {
          csp: { resourceDomains: IMAGE_DOMAINS },
          // The view draws its own cards and sheet; a host frame around it
          // just doubles the border in the grid case.
          prefersBorder: false,
        },
        // ChatGPT reads these two off the resource. The description is what
        // its model is told the widget shows, so it can decide when the
        // inline view answers the question and prose is unnecessary.
        "openai/widgetDescription":
          "An inline product grid: each card rotates the listing's photos, and clicking one opens the product's full detail in place — photos (click one to view it full size), video, price, rating, seller and buyer reviews. For sellers it renders the created/updated listing as a card, and — when a listing still needs its photo — a drag-and-drop upload zone that attaches the seller's original photo and video files to the listing losslessly and activates it.",
        "openai/widgetPrefersBorder": false,
      },
    }],
  });
  const config = { description: "Inline product grid for Firestarter shopping results (photos, price, buyability)." };
  registerAppResource(server, "Firestarter shopping results", SHOPPING_RESULTS_URI, config, serve(SHOPPING_RESULTS_URI));
  registerAppResource(server, "Firestarter shopping results (stable)", SHOPPING_RESULTS_STABLE_URI, config, serve(SHOPPING_RESULTS_STABLE_URI));
}
